[tool.poetry]
name = "hobby__ledmatrix"
version = "0.1.0"
description = ""
authors = ["Koen Baak <koen.baak@mn.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
